### ISSUE TITLE
Duplicate "amTimeAgo" name usage - filter unusable

### ISSUE THREAD

**Issue by GabiAxel** [urish/angular-moment#105]
"amTimeAgo" is used both for a directive and for a filter, which makes the filter (registered second) amTimeAgo unusable. One of them needs to be renamed.

**Comment by urish** [comment]
Hi @GabiAxel , 

It should work regardless of both the directive and the filter having the same name, see example code in the [this test case](https://github.com/urish/angular-moment/blob/d2e1840e94d31efcda228093fb9ca624c03be182/tests.js#L516). 

If you have a specific scenario where it doesn't work, please create a demo plunkr/test case that demonstrates the problem and we will seek for a solution.

Thanks!
