### ISSUE TITLE
Error: [$parse:ueoe] Unexpected end of expression: Ui.turnOn('modal2'…

### ISSUE THREAD

**Issue by raywu** [urish/angular-moment#106]
I have been trying to access SharedState (core) in my controller, but am not having much luck.

In the context of setting up Modal: at first I tried to access Ui like the Doc suggests by using ng-click="Ui.turnOn('myVar')"

This throws an error: 
<pre>
Error: [$parse:ueoe] Unexpected end of expression: Ui.turnOn('modal2'
http://errors.angularjs.org/1.3.8/$parse/ueoe?p0=Ui.turnOn('modal2'
    at http://0.0.0.0:9000/bower_components/angular/angular.js:63:12
    at Parser.consume (http://0.0.0.0:9000/bower_components/angular/angular.js:12035:13)
    at Parser.functionCall (http://0.0.0.0:9000/bower_components/angular/angular.js:12310:10)
    at Parser.primary (http://0.0.0.0:9000/bower_components/angular/angular.js:11982:24)
    at Parser.unary (http://0.0.0.0:9000/bower_components/angular/angular.js:12258:19)
    at Parser.multiplicative (http://0.0.0.0:9000/bower_components/angular/angular.js:12241:21)
    at Parser.additive (http://0.0.0.0:9000/bower_components/angular/angular.js:12232:21)
    at Parser.relational (http://0.0.0.0:9000/bower_components/angular/angular.js:12223:21)
    at Parser.equality (http://0.0.0.0:9000/bower_components/angular/angular.js:12214:21)
    at Parser.logicalAND (http://0.0.0.0:9000/bower_components/angular/angular.js:12205:21) <button ng-click="Ui.turnOn('modal2'">
</pre>

I tried to pass in the SharedState service, but this is undefined.

<pre>
angular.module('MagicBus')
  .controller('Ctrl', ['$rootScope', '$scope', '$state', 'SharedState',
  function UpcomingTripsCtrl($rootScope, $scope, $state, SharedState) {
    …code…
}
</pre>

This is how the Mobile Angular UI is loaded, my understanding is that core should be part of the dependencies already.

<pre>
var app = angular.module('MagicBus', [
  'mobile-angular-ui',
  'mobile-angular-ui.plugins.ui-router',
  'ui.router',
]);

**Comment by urish** [comment]
Hi @raywu , are you sure that you posted this in the right place? I don't see how this is related to `angular-moment` in any way...

**Comment by raywu** [comment]
@urish Hey Uri, thanks. You're right. I had two windows open. Thanks!

**Comment by AmarJagtapDev** [comment]
**hide this code in ng-grid.js - it add extra column when group is add.**  
/moved out of above loops due to if no data initially, but has initial grouping, columns won't be added
        if(cols.length > 0) {
            for (var z = 0; z < groups.length; z++) {
                if (!cols[z].isAggCol && z <= maxDepth) {
                    cols.push(new ngColumn({
                        colDef: {
                            field: '',
                            width: 25,
                            sortable: false,
                            resizable: false,
                            headerCellTemplate: '<div class="ngAggHeader"></div>',
                            pinned: grid.config.pinSelectionCheckbox
                            
                        },
                        enablePinning: grid.config.enablePinning,
                        isAggCol: true,
                        headerRowHeight: grid.config.headerRowHeight
                        
                    }, $scope, grid, domUtilityService, $templateCache, $utils));
                }
            }
        }
