### ISSUE TITLE
How to set Relative Time strings

### ISSUE THREAD

**Issue by sabrehagen** [urish/angular-moment#109]
The docs at http://momentjs.com/docs/#/customization/relative-time/ show how to change the relative time strings. Can we configure them through the angularMomentConfig constant object?

**Comment by nlkluth** [comment]
AngularMoment exposes the moment variable [See here](https://github.com/urish/angular-moment/blob/master/angular-moment.js#L88)

You can pass this into your controller or config to update it.

Example:
```js
  angulare.module('app', ['angularMoment'])
  .controller('MainCtrl', function($scope, moment) {
    moment.lang('en', {
    relativeTime : {
      future: 'in %s',
      past:   '%s ago',
      s:  'seconds',
      m:  '1 minute',
      mm: '%d minutes',
      h:  'an hour',
      hh: '%d hours',
      d:  '1 day',
      dd: '%d days',
      M:  '1 month',
      MM: '%d months',
      y:  '1 year',
      yy: '%d years'
    }
  });
});
```

**Comment by sabrehagen** [comment]
thank you very much!

**Comment by sabrehagen** [comment]
Just an update, lang() is deprecated, so locale() should be used. Also, in your example 's' should be '%d seconds'. See below:

    moment.locale('en', {
        relativeTime : {
            future : 'in %s',
            past   : '%s ago',
            s      : '%d seconds',
            m      : 'a minute',
            mm     : '%d minutes',
            h      : 'an hour',
            hh     : '%d hours',
            d      : 'a day',
            dd     : '%d days',
            M      : 'a month',
            MM     : '%d months',
            y      : 'a year',
            yy     : '%d years'
        }
    });

**Comment by lpradoe** [comment]
Hi, is there a way to represent the time in weeks? for example, if there's a post that was created a month ago, I would like to show 4w (4weeks) instead of 1m (1month)

**Comment by urish** [comment]
You can indeed configure moment js to do so, see this SO answer for example:

http://stackoverflow.com/a/29855624/830623

**Comment by lpradoe** [comment]
Great! Thank you!
