### ISSUE TITLE
UTC to local time

### ISSUE THREAD

**Issue by Hesesses** [urish/angular-moment#114]
My app gets utc datetime value from backend ('2015-03-03 11:18:33' for example)

How to convert this to user's local time?

**Comment by pvantrepote** [comment]
I have the same issue, I can't find a way to call .local() after utc().
Idea, change the preprocess config to be an array.
preprocess = ['utc', 'local']

**Comment by pvantrepote** [comment]
I did a quick test, and this is working:

this.preprocessors = {
					utc: moment.utc,
					local: function(aMoment) {
						if (!moment.isMoment(aMoment)) {
							$log.warn('angular-moment: Ignoring unsupported value for local preprocess: ' + aMoment);
							return aMoment;
						}

						return aMoment.local();
					},
					unix: moment.unix
				};

				this.preprocessDate = function (value, preprocess, format) {
					if (angular.isUndefined(preprocess)) {
						preprocess = angularMomentConfig.preprocess;
					}

					if (preprocess instanceof Array) {
						var previousResult = value;
						var $this = this;

						preprocess.forEach(function(pre) {
							previousResult = $this.preprocessDate(previousResult, pre, format);
						});

						return previousResult;
					}

					if (this.preprocessors[preprocess]) {
						return this.preprocessors[preprocess](value, format);
					}
					if (preprocess) {
						$log.warn('angular-moment: Ignoring unsupported value for preprocess: ' + preprocess);
					}
					if (!isNaN(parseFloat(value)) && isFinite(value)) {
						// Milliseconds since the epoch
						return moment(parseInt(value, 10));
					}
					// else just returns the value as-is.
					return moment(value, format);
				};

**Comment by circuitrider** [comment]
What is "this" in this context for your snippet?

**Comment by jwohlfert23** [comment]
+1

**Comment by pvantrepote** [comment]
this is the amMoment service.
If you want to my snippet just replace those 2 methods in the amMoment service by the one in the snippet.

**Comment by staff0rd** [comment]
this worked great, thanks!

**Comment by dibayendu** [comment]
This has worked for me:

```
(function() {
  'use strict'

  angular
    .module('myApp')
    .run(function (moment, amMoment) {
      moment.tz.setDefault("utc");  // make sure to include moment-timezone.js
      amMoment.changeTimezone('Australia/Melbourne');
    });
})();
```

**Comment by purdel** [comment]
I also have this issue. In my case the timestamp is saved as UTC on the server, while the users should view the date in their own local time without explicitly declaring it. Modifying the service is a no-go as future bower updates will probably destroy the edits.

**Comment by urish** [comment]
We will add a `amLocal` filter to 1.0.0

**Comment by purdel** [comment]
nice
