### ISSUE TITLE
Support for Time from X

### ISSUE THREAD

**Issue by duncanmcdowell** [urish/angular-moment#115]
This would be a useful directive for automatic view binding of time remaining in situations where you want to emulate a countdown. Essentially, the opposite of time ago.  [Moment Js docs on Time from X](http://momentjs.com/docs/#/displaying/from/)

**Comment by urish** [comment]
Perhaps the `amDifference` directive (introduced by #120) fits this use-case?

**Comment by jdupl** [comment]
:+1: for this feature

@urish `amDifference` does not choose the default unit of time like `am-time-ago`.

**Comment by baleato** [comment]
I'm opening a PR(https://github.com/urish/angular-moment/pull/145) about using an `am-from` attribute:
```
<span am-time-ago="message.time" am-from="from"></span>
```
What do you think about it?

**Comment by urish** [comment]
Implemented as of #145, released as 0.10.2
