### ISSUE TITLE
angularMomentConfig.format is not working

### ISSUE THREAD

**Issue by diimpp** [urish/angular-moment#116]
Hi,

I'm trying to set default date format like this
```
 .constant('angularMomentConfig', {
     preprocess: 'utc',
     timezone: 'Europe/Berlin',
     format: 'HH:mm:ss, DD MMMM YYYY',
 })
```
```
{{ query.created_at|amDateFormat }}
```
But I'm shown timestamp ```2015-03-06T11:10:15+01:00```

I don't see any calls for this property in filters. Is it correct?

Regards.

**Comment by cyril-blanco** [comment]
Hi,

Based on what I understand from the source code, angularMomentConfig.format is used only in "amTimeAgo".

@urish is it a missing feature or something intentional?

**Comment by cyril-blanco** [comment]
Ok, after digging a bit more, it appears that angularMomentConfig.format is the default *input* format. Therefore it shouldn't be used to set a default *output* format. In fact, default date format is not something angular-moment should handle: this is a moment.js job. 

Try configuring the momentjs locale: http://momentjs.com/docs/#/i18n/

**Comment by diimpp** [comment]
Thank you for your reply, @cyril-blanco 

I don't see how it can be set with locale options in the momentjs, but I'm not that interested now.
Still can be useful to add default format for filters.

Closing as angularMomentConfig.format is correct as you pointed out.

Regards.

**Comment by cyril-blanco** [comment]
Well, I looked at moment.js default format(): it turns out that it is configured by setting moment.defaultFormat, which is obviously not locale dependent.

I finally implemented this functionality using a custom filter:
```javascript
angular.module('anyModule', []).filter('myDateFormat', function($filter) {
	var amDateFormatFn = $filter('amDateFormat');
	return function(value, format, preprocess) {
		if (typeof format === 'undefined') {
			format = 'LL';
		}
		return amDateFormatFn(value, format, preprocess);
	}
});
```

Warning: reformated code, untested (I'm not writing it like this in my real implementation, but I got it working)

@urish what do you think about this?

**Comment by miukki** [comment]
yeah i also did something:   .filter('moment',  ['$filter', function ($filter) {
    return function (input) {
      var date = $filter('amUtcOffset')(input, '+0700');
      return $filter('amDateFormat')(date, 'MM.DD.YYYY HH:mm:ss')
    };
  }])
