### ISSUE TITLE
Use $timeout rather than setTimeout

### ISSUE THREAD

**Issue by bbodenmiller** [urish/angular-moment#118]
Per John Papa's Angular style guide it is better to use $timeout rather than setTimeout: https://github.com/johnpapa/angular-styleguide#timeout-and-interval

**Comment by urish** [comment]
In most of the cases, that is correct. However, there is a performance penalty when one uses `$timeout`, and it can also cause problems with you protractor end-to-end testing scenarios. See #5 and #66 for discussion. 

One proposed solution was to use `$interval` and passing false in `invokeApply`. This should both skip the digest cycle and play nicely with protractor. However, the `invokeApply` parameter seems to be [broken](https://github.com/angular/angular.js/issues/7103) in AngularJS 1.2. Also, using `$interval` will probably result in a more complicated code.

Therefore, using `setTimeout()` is still the best solution for angular-moment.
