### ISSUE TITLE
npm install angular-moment fails

### ISSUE THREAD

**Issue by andrenarchy** [urish/angular-moment#121]
The fresh release 0.9.1 fails to install via npm if bower is not installed. The package.json now contains the line
```
"postinstall": "bower install"
```
I guess an npm package shouldn't rely on bower to be installed and the line should be removed.

**Comment by nschloe** [comment]
+1. This has already caused build issues for us:
```
> angular-moment@0.9.1 postinstall /home/rollout_frontend/mirror/branches/compact-margin-discussions/node_modules/angular-moment
> bower install

sh: bower: command not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by urish** [comment]
This is probably a side effect of #107. Removing it makes sense...

**Comment by urish** [comment]
@nschloe @andrenarchy can you please have a look at [this commit](https://github.com/urish/angular-moment/commit/27b1260c0436d91be317ce2c10ac15fcfa213a14)?

**Comment by urish** [comment]
Fix released as 0.9.2

**Comment by andrenarchy** [comment]
It feels wrong to call one package manager from another. npm and bower are two different package managers. It's nice to make a package available in both of them – but in my opinion the package shouldn't depend on another package manager.

Can't you satisfy the npm package dependencies with npm?

**Comment by urish** [comment]
Hi @andrenarchy , happy to read that the fix is working for you :)

The idea behind calling `bower` from within npm is to simplify the process for [contributors](https://github.com/urish/angular-moment/blob/master/CONTRIBUTING.md) - so those who are not familiar with bower will not have to install it globally. Perhaps a even better solution would be to just use npm for all the dependencies...

**Comment by andrenarchy** [comment]
I think the current solution is OK since it doesn't assume that bower is installed.
