### ISSUE TITLE
Uncaught TypeError: Cannot read property 'module' of undefined       

### ISSUE THREAD

**Issue by kirangsa** [urish/angular-moment#130]
Hello,
 When am adding angular-moment its throughing following error
 
Uncaught TypeError: Cannot read property 'module' of undefineda @ angular-moment.min.js:1i.execCb @ require.js:29Z.check @ require.js:18Z.enable @ require.js:23Z.init @ require.js:17E @ require.js:14i.completeLoad @ require.js:28i.onScriptLoad @ require.js:29

**Comment by urish** [comment]
Can you please try switching to the non-minified version so we will get a correct line information?

Also, please provide details on your environment. Thanks!

**Comment by kirangsa** [comment]
Hi Urish,

Thanks for the response


am using requre for AMD.

this is my requre file

require.config({
    baseUrl: 'js',
    paths: {
        'jquery':'lib/jquery',
        'jqueryui':'lib/jquery-ui.min',
        'modernzr': 'lib/modernizr',          
        'angular': 'lib/angular.min',
        'angular-route': 'lib/angular-route.min',          
        'angular-animate': 'lib/angular-animate.min',
        'app-start': 'custom/common/app-start',
        'app-route': 'custom/common/app-route',
        'factory': 'custom/common/factory',
        'filter': 'custom/common/filter',
        'constants': 'custom/common/constants',
        /*User defined Files to go here*/
        'bootstrap': 'lib/ui-bootstrap-tpls-0.12.1.min',
        'selectBoxIt': 'lib/jquery.selectBoxIt.min',
        "moment": 'lib/moment',
        "angular-moment": 'lib/angular-moment',
        'login': 'custom/controllers/loginCtrl',
        'dashboard' :'custom/controllers/dashboardCtrl',
        'projectView' :'custom/controllers/projectViewCtrl',
        'projectViewDir' :'custom/directives/projectViewDir'
    },
    shim: {
        'angular-animate': ['angular'],
        'angular-route': ['angular', 'angular-animate'],
        'app-start': ['angular-route'],
        /*User defined files to go here*/
        'login': ['angular'],
        'dashboard': ['angular'],
        'projectView' :['angular'],
        'bootstrap':['jquery'],
        'selectBoxIt': ['jquery', 'jqueryui']
        
    },
    wrapShim: true
});

require(['app-start']);

**Comment by mpreziuso** [comment]
Same is happening to me, similar environment, but I am also using `angularAMD`.

**Comment by urish** [comment]
Can you please add a console.log to the [if statement at the end of the code](https://github.com/urish/angular-moment/blob/master/angular-moment.js#L555) to see which of the statements there is executed?

**Comment by kirangsa** [comment]
Hi urish,

Same error is happening again.   i think the global moment is not available thats why its happening.

* @description
     * moment global (as provided by the moment.js library)
     */
    app.constant('moment', moment)

**Comment by mpreziuso** [comment]
Hi @urish, in my case, the first if statement is getting executed.
Angular seems undefined, while moment seems ok.

**Comment by urish** [comment]
Should be fixed by 1.0.0-beta.1. 

If this still happens, please reopen.
