### ISSUE TITLE
Custom Duration Formats

### ISSUE THREAD

**Issue by alexg313** [urish/angular-moment#132]
Does the 'amDurationFormat' filter allow for custom formats? I want to display my duration as HH:MM:SS. I tried the line below with no luck. 

{{ myDuration | amDurationFormat:'HH:MM:SS' }}

Thanks!

**Comment by urish** [comment]
It gets format as a parameter, but the format is used for parsing the input value (it is passed as the second parameter to `[moment.duration()](http://momentjs.com/docs/#/durations/creating/)`). 

The duration value is formatted using the `[humanize](http://momentjs.com/docs/#/durations/humanize/)` method. See moment/moment#463 for a discussion about adding this feature to moment.js.
