### ISSUE TITLE
Inline sourcemap with the minified code.

### ISSUE THREAD

**Issue by diosney** [urish/angular-moment#134]
Instead of having in the `.min.js` file:

    //# sourceMappingURL=angular-moment.min.js.map

can you include the sourcemap file at the bottom of the minified script?

This is so when concatenating vendor files a single file the browser don't complain for not being able to locate the sourcemap at the destination.

Thanks

**Comment by urish** [comment]
@diosney Hi, you are invited to send a PR that will create another version of the minified script with the sourcemap inlined.

Thanks!

**Comment by leocaseiro** [comment]
I have the issue, however, different of Gulp, the Grunt Uglify doesn't have this option: https://github.com/gruntjs/grunt-contrib-uglify/issues/158
