### ISSUE TITLE
Can I set timezone dynamically?

### ISSUE THREAD

**Issue by skfd** [urish/angular-moment#135]
I'm getting timezone info in ajax request so I want to set timezone dynamicly. Can this be done?

**Comment by mmccook** [comment]
I just set it using
```javascript
moment.tz.setDefault("America/Los_Angeles"); 
```

**Comment by urish** [comment]
As of 1.0.0-beta.1, you can set it dynamically using the `amMoment` service:

```js
amMoment.changeTimezone('America/Los_Angeles');
```
