### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: amMomentProvider <- amMoment <- myService

### ISSUE THREAD

**Issue by roughy** [urish/angular-moment#136]
Hi,

I successfully integragted angular-moment into my project. But I'm struggling when it comes to testing.

I have Karma (with jasmine) running the tests. But after I added amMoment to myService, almost all my tests fail with the above error.

I need amMoment to change locale.

My karma.conf.js includes 

            'app/bower_components/moment/moment.js',
            'app/bower_components/angular-moment/angular-moment.js',

How can I make Karma handle amMoment?

**Comment by roughy** [comment]
ok the following line was missing in my tests

```
beforeEach(function() {
    module('angularModule');
});
```

**Comment by urish** [comment]
Thank you @roughy for sharing your findings!
