### ISSUE TITLE
Serious typo in readme.md

### ISSUE THREAD

**Issue by levelibeeka** [urish/angular-moment#142]
I've been trying to find out why the module doesn't work for hours, then I found that there's a typo in readme.md:

```html
<span an-time-ago="message.time"></span>
<span an-time-ago="message.time" am-preprocess="unix"></span>
```
It should be

```html
<span am-time-ago="message.time"></span>
<span am-time-ago="message.time" am-preprocess="unix"></span>
```
Thanks!

**Comment by urish** [comment]
Are you referring to [This file](https://github.com/urish/angular-moment/blob/master/README.md)? 

It says `am-time-ago`, not `an-time-ago`...

**Comment by levelibeeka** [comment]
Hm, quite strange. I copy-pasted it and I could swear I saw it in that file... Then I didn't copy it and it was because my eyes were playing a joke on me (monospace `m` vs `n` seemed quite similar after staring the screen for 10 hours).

Sorry for the false alarm!

**Comment by urish** [comment]
No worries, thanks for altering anyway :)
