### ISSUE TITLE
Unknown provider: amDateFormatFilterProvider

### ISSUE THREAD

**Issue by jaytaylor** [urish/angular-moment#144]
Yesterday after adding angular-moment to my app, I was getting the following error anytime I tried to use `amDateFormat`:

    Unknown provider: amDateFormatFilterProvider

https://docs.angularjs.org/error/$injector/unpr?p0=amDateFormatFilterProvider

I struggled with this error for awhile, and eventually reordered the JS resource file load order to put moment.js and angular-moment.js right after the core angular.js libs.  Then the issue went away.

However, reverting the load order no longer produces the issue.

I'm presently at a loss to explain why it is not reproducible.  Just wanted to document my experience here in case others run into the issue or can explain why this happens.

**Comment by urish** [comment]
Thanks for sharing!

My bet would be some caching issue....

Uri

**Comment by jaytaylor** [comment]
I know right?

I was ctrl-shift-R'ing the whole time..

though if I had to guess, like you I would go with some kind of caching
issue.

**Comment by devourment77** [comment]
I am running into this issue as well, is shuffling the js files really the way to fix?

**Comment by Maury1329** [comment]
Hi All,
Except for changing the load order, did you manage to find out what causes this?
I have the same issue, but loading in any order whatsover, does not solve the issue.

**Comment by priyasaini** [comment]
I am facing this issue only on production server. Did u get a resolution for this?

**Comment by Maury1329** [comment]
Loading the modules 'moment' and 'angularMoment' in index.html will give the error.
You should load them lazily.
Try [this](https://oclazyload.readme.io/docs/with-your-router) method.
Something like this will work, with the modules in the order as shown:
`resolve: {
	loadMyCtrl: ['$ocLazyLoad', function($ocLazyLoad) {
		 return $ocLazyLoad
		.load([  
				'bower_components/moment/min/moment.min.js',
				'bower_components/angular-moment/angular-moment.min.js'
				]
		 );
	}]
}
`
