### ISSUE TITLE
output fallback in case of null datetime?

### ISSUE THREAD

**Issue by enapupe** [urish/angular-moment#150]
How do you guys deal with am-time-ago when the model's datetime is `null`? The design I've got is "show the time or show a `-`", so, I have to  add ng-if to all am-time-ago to check if the model is not `null`, also, i have to add an span with the opposite if to display the `-` thing.

I'm not suggesting that this directive should have a fallback option value, I'm more like asking how do you guys solve this kind of issue?

example:
`<p ng-if="contact.last_email_interaction" am-time-ago="contact.last_email_interaction"></p>
<p ng-if="!contact.last_email_interaction">- - -</p>`

(I think this is ugly)

**Comment by enapupe** [comment]
Nevermind! I could've just done:
`<p ng-bind="(contact.update_date | amTimeAgo) || '-'"></p>`

**Comment by enapupe** [comment]
Or maybe even better, using css `:empty` together with `::after`

**Comment by urish** [comment]
@enapupe thanks for sharing your solution!
