### ISSUE TITLE
am-time-ago directive showing wrong time. TimeZone bug. 

### ISSUE THREAD

**Issue by promactkaran** [urish/angular-moment#157]
I am +5:30GMT Time.

and my directive is like this : 

< p am-time-ago="update.date"> < / p>           // 2015-08-05T04:55:58.583Z 

in the source code.
now = moment()      // returns a unix stamp 1438752881827   -- approx. to 2015-08-05T05:34:41.990Z

I get "40 min ago", though it's correct calculation - but the current time is **moment() + the time zone** 
My post was created nearly 12 hours ago, but all i get is 40 min ago. 
Are timezones not considered while calculating the am-time-ago ? Help!

**Comment by urish** [comment]
Seems like the difference between the two dates is indeed about 40 minutes.

`2015-08-05T04:55:58.583Z` 
`2015-08-05T05:34:41.990Z`

Note that the 'Z' at the end indicates that the time is specific in UTC timezone.
