### ISSUE TITLE
Feature Request: duration with remainder

### ISSUE THREAD

**Issue by twisty7867** [urish/angular-moment#158]
Either a new filter or a parameter for `amDurationFormat` that would express a duration with a remainder. Example:

Input | amDurationFormat output | new feature output
-------|------------------------------------|--------------------------
2500 seconds | an hour | 41 minutes, 40 seconds
3600 seconds | an hour | an hour
4600 seconds | an hour | one hour, 17 minutes
1440 minutes | a day | a day
1565 minutes | a day | one day, two hours

**Comment by urish** [comment]
Hi, thank you for suggesting this feature!

The duration value is formatted using the [humanize](http://momentjs.com/docs/#/durations/humanize/) method. See moment/moment#463 for a discussion about adding this feature to moment.js.

**Comment by prusswan** [comment]
Right now this needs be done via jsmreese/moment-duration-format, you can add your own directive for it.
