### ISSUE TITLE
Manipulate filters

### ISSUE THREAD

**Issue by LennyLip** [urish/angular-moment#159]
Thanks for cool app!

What about Manipulate filters?

http://momentjs.com/docs/#/manipulating/

like a

    function addFilter(value, count, type, preprocess, suffix) {
                if (typeof value === 'undefined' || value === null) {
                    return '';
                }
               date = moment(value);
                if (!date.isValid()) {
                    return '';
                }

                date.add(count, type);

etc...

**Comment by urish** [comment]
@LennyLip Sounds like a good idea :)

Pull requests are always welcome, see the [Contributing Guide](https://github.com/urish/angular-moment/blob/master/CONTRIBUTING.md) for instructions...
