### ISSUE TITLE
amDateFormat not updating when statefulFilters set to false

### ISSUE THREAD

**Issue by rwilliams-scottlogic** [urish/angular-moment#160]
Angular's (at least 1.3.4 and later) `expressionInputDirtyCheck` function will consider objects to be equal if they have the same valueOf() value. One such case is two Moments representing the same instant in time but in different time zones.

This means that if you change the value that the filter input is bound to between two such Moments, Angular will consider them equal and won't run the filter. So your UI ends up displaying the wrong value.

The issue won't be causing problems to most users, due to all angular-moment filters being declared as `stateful` by default to support the time zone and language switching.

**Comment by urish** [comment]
Thanks for sharing the information, as you say, the workaround is to use stateful filters.
