### ISSUE TITLE
Cannot convert local moment to UTC

### ISSUE THREAD

**Issue by ramprakash-ravi** [urish/angular-moment#163]
I'm trying to get unix timestamp and UTC converted for same for date using moment. But i'm getting same local values for both:

```
var local_date = moment();
var dateUnix = local_date.unix();
var dateUnixUTC = local_date.unix();

console.log(dateUnix);
console.log(dateUnixUTC);

//prints
1440056684
1440056684
```

**Comment by urish** [comment]
```
   var dateUnix = local_date.unix();
   var dateUnixUTC = local_date.unix();
```

These two lines are doing the exact same thing, so it makes sense that you will get the same result.

Anyway, this is not the place for moment.js related questions. Please use the [official moment.js repository](https://github.com/moment/moment) for moment.js related issues / questions. You can also ask on stackoverflow.
