### ISSUE TITLE
Loading moment-timezone when using Browserify

### ISSUE THREAD

**Issue by ginovva320** [urish/angular-moment#164]
Is there a way to load moment-timezone instead of moment when using this module with browserify? Since I'm using browserify, angular-moment loads moment via `require('moment')`, which won't load moment-timezone. 

I can change that line to the following `angularMoment(angular, require('moment-timezone'));` and it works for me, but obviously would not work for those who just want to use moment.

**Comment by urish** [comment]
Did you try requiring `moment-timezone` before angularMoment? I think it should do the trick...

**Comment by ginovva320** [comment]
That did work, thanks!
