### ISSUE TITLE
Setting a "from" and a "to" timezone?

### ISSUE THREAD

**Issue by ThinklabsGbR** [urish/angular-moment#165]
Hey guys,

im wondering if it is somehow possible to use a "from" timezone and "to" timezone. Im using Timezones from "Europe/London" and want to use the amTimeAgo directive to show the user the difference in its specific timezone, i.e. "America/Los_Angeles".

Im using the following format im by database: 2015-08-23 21:22:28

Im really thankful for any help!

**Comment by urish** [comment]
@ThinklabsGbR this should be achievable by setting the `angularMomentConfig.timezone` to Europe/London, e.g.

```js
angular.module('myapp').config(function(angularMomentConfig) {
    angularMomentConfig.timezone = 'Europe/London';
});
```

`am-time-ago` should automatically display the relative date based on the user's machine time, and it should take into account his locally configured timezone.
