### ISSUE TITLE
Timezones with a 'Z' somewhere in them all become UTC

### ISSUE THREAD

**Issue by james-a-woods** [urish/angular-moment#168]
I was trying to use the timezone 'Europe/Zurich' but it was always coming back as UTC.

The problem seems to be the regular expression match in applyTimezone

    if (timezone.match(/Z|[+-]\d\d:?\d\d/gi)) {
        aMoment = aMoment.utcOffset(timezone);

I was able to work around the problem by using 'Europe/Amsterdam'.  But I did waste quite some time trying to work out what the problem was.

**Comment by urish** [comment]
Good catch, will fix this in the upcoming release (just a few days ahead)

**Comment by urish** [comment]
Fix released as part of 0.10.3
