### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by fcristel** [urish/angular-moment#179]
Hi

Is it possible to style the output from am-time-ago? I want to have different styles, depending on the string. For example:

If the output is: "10 minutes ago", I want to have the "10" applied a special css class.
Then, when it changes to "a day ago", I want the "day" part with a special css class.
When it changes to "Thursday, 10th of June" for example, applying some css class to the different parts of the string. One for the day, another maybe for the month, etc. 
And so on, to cover all the different formats that it outputs, past and future. 

Thanks!

**Comment by urish** [comment]
It is not directly supported by the library. I believe you can work around this, by changing the locale strings to include HTML, and then using the `amTimeAgo` filter together with `ng-bind-html`. For more information about changing the locale strings, please see #109.
