### ISSUE TITLE
changeLocale doesn't work

### ISSUE THREAD

**Issue by iain17** [urish/angular-moment#180]
Tried everything. Like proposed:
angular.module('NF').run(function(amMoment) {
    amMoment.changeLocale('nl');
});
even injected amMoment in controller and called amMoment.changeLocale('nl');
Also tried doing it with each state change, since I use ui router. But no success.

Yes I've added the nl locale found here: https://github.com/moment/moment/blob/develop/locale/nl.js
Using meteor package: https://atmospherejs.com/jasonaibrahim/angular-moment
What am I missing here?

**Comment by mokipedia** [comment]
I kind of have the same issue with german.
Point is, it was working before, and I do not think we changed something since this was tested.

**Comment by urish** [comment]
Hi, thanks for reporting!

Can you please create a small plunker demonstrating the issue?

Thanks!

**Comment by mokipedia** [comment]
hmm my plunker gives me the expected behavior. I am searching for a difference right now.

**Comment by mokipedia** [comment]
ok i found my problem lying in an incompatibility with another bower component:
angular-timer uses humanize-duration which loads moments not in "moment" package but in "momentjs". and as this package is loaded after your file. it is the moment instance to be used.

any sugghestions how to fix this?

**Comment by mokipedia** [comment]
my issue is completely not your fault. I have resides in another bower component using a nonofficial bower package for moment.js (angular-timer)
I created an issue there.

**Comment by urish** [comment]
great, thanks for the update :-)

Good luck with your project man!

**Comment by iain17** [comment]
@mokipedia might be me, but it still shows the english version here: http://puu.sh/pJudi/4f6de91e9e.png of your plunker example, even though you've set it to german.

**Comment by mokipedia** [comment]
You know, that your screenshot shows the info page, right? ^^
You have to click on the "eye" icon to the right where it says "live preview".
It then Says "Hello World, Dienstag, 28.06.2016", which is correctly translated.

**Comment by iain17** [comment]
@mokipedia Ah yes sorry my mistake. Used to another website that insantly runs it. You're correct it does work on your plunker example, however it just won't run on my version.
Anyways, I didn't have the same error. I'm using two meteorJS packages which repack this project: 
https://atmospherejs.com/rgnevashev/angular-moment
https://atmospherejs.com/rzymek/moment-locale-nl
However putting that nasty hack that works for me inside a angular.run should run it once I suppose.

**Comment by mokipedia** [comment]
I am a little bit confused now:
You are loading angular-moment which requires and loads moment.js via the bower package "moment" (which is the official moment package for bower), which also has the nl location file right with it. (bower_components/moment/locale/*).
And then you are loading moment-locale-nl from rzymek, which loads the meteor package for moment and most likely will load moment itself? 
May I ask why? The locale file in the given bower_component should definitely work fine and the missmatch could very well be the same error I had in a different way.
