### ISSUE TITLE
Unknown provider errors

### ISSUE THREAD

**Issue by anisylen** [urish/angular-moment#181]
I'm getting unknown provider errors for all the filters despite injecting the 'angularMoment' as a dependency.

"Error: [$injector:unpr] Unknown provider: amParseFilterProvider <- amParseFilter"

What other info do I need to provide?

**Comment by urish** [comment]
`amParse` is only available in the beta version of angular-moment 1.0. Please check that you are using this version (you can look at the first line of angular-moment.js to determine the version).

**Comment by anisylen** [comment]
Thanks! I fetched from bower where the latest version is 0.10.x

**Comment by urish** [comment]
Yes, this is the latest stable version on bower. You can explicitly specify 1.0.0-beta.2 to get the latest beta

**Comment by anisylen** [comment]
Yeah, I did just that and it works. Thanks a ton!

**Comment by adrijardi** [comment]
Great work, but a comment on https://github.com/urish/angular-moment pointing out that the doumentation is for beta 2.

Thanks a lot!

**Comment by urish** [comment]
@adrijardi good idea!

**Comment by seawenzhu** [comment]
sdfsfdsfsdafdsafsaf

**Comment by joaquinrivero** [comment]
Same issue, 1.0.0-beta.6
