### ISSUE TITLE
Support for startOf, endOf

### ISSUE THREAD

**Issue by vikbez** [urish/angular-moment#184]
This would be really useful (supported from momentjs 1.7.0)

for example:

```javascript
{{ date | amStartOf:'month' | amLocal }}
{{ date | amEndOf:'day' | amLocal }}
```

links:
http://momentjs.com/docs/#/manipulating/start-of/
http://momentjs.com/docs/#/manipulating/end-of/

**Comment by kdeldycke** [comment]
:+1:

**Comment by urish** [comment]
Sounds like a great idea, can you please send a PR with these filters?

Thanks!

**Comment by urish** [comment]
@vikbez are you interested in sending a PR for this features?

**Comment by vikbez** [comment]
Yes, but I'm currently quite busy, so if you want to do it, free to you or else wait a little :)

Thanks

**Comment by urish** [comment]
@vikbez great, thanks! I will wait for it then :)

**Comment by vikbez** [comment]
closed because https://github.com/urish/angular-moment/pull/203
