### ISSUE TITLE
Add unix offset formatting filters

### ISSUE THREAD

**Issue by solomon87** [urish/angular-moment#187]
Would like a filter to format moment to unix timestamp formats. This would be a helpful utility for working with other types of functionality. My particular situation involves sorting elements via the Isotope library. http://isotope.metafizzy.co/sorting.html

**Comment by urish** [comment]
You can use `amDateFormat` filter with the 'X' or 'x' format specifiers. Read here for more information about supported formatting options:

http://momentjs.com/docs/#/displaying/format/

**Comment by solomon87** [comment]
Thank you for pointing that out
