### ISSUE TITLE
Unknown provider: amFromUnixFilterProvider <- amFromUnixFilter

### ISSUE THREAD

**Issue by singhmohancs** [urish/angular-moment#188]
Below code produce error
``````````
{{listCtrl.createdDate | amFromUnix | amCalendar }}
``````````
please help on this. 

I have installed angular-moment using ````bower install angular-moment --save```` , still i can see the difference in angular-monent.js file 

In bower component file amFromUnix this filter does not exists , but on github this filter exists.

**Comment by urish** [comment]
Hi, for using `amFromUnix` you need to install version 1.0.0-beta.2, e.g. 

    bower install angular-moment#1.0.0-beta.2 --save
