### ISSUE TITLE
What's the time-ago filter?

### ISSUE THREAD

**Issue by mirague** [urish/angular-moment#192]
I want to display the time ago (e.g. "a few seconds ago") in a tooltip when an icon is hovered, like so:

```
<span class="time">
    <i class="icon-star" tooltips tooltip-title="You added this {{ favourite.favourited_at | amUtc | amLocal | amDateFormat:'YYYY-MM-DD HH:mm:ss' }}"></i>
</span>
```

How can I do this? I can't find anything like this in the docs.

**Comment by urish** [comment]
We do have an `amTimeAgo` filter. It is not documented (as it should be), but you can still use it.

https://github.com/urish/angular-moment/blob/9680d6f1d21585e40f32e1de8f002e64daf20906/angular-moment.js#L589

**Comment by mirague** [comment]
I found it shortly after opening this issue, thanks for your time and apologies for not looking more thorough before posting!
