### ISSUE TITLE
Not working in iphone

### ISSUE THREAD

**Issue by Suresh-R-S** [urish/angular-moment#197]
Great work..
But this functionality is not supported in iphone..
any idea??

**Comment by urish** [comment]
Can you please create a plunkr or a gist that reproduces the issue?

Thanks

**Comment by Suresh-R-S** [comment]
we are not getting the issue in browser, the issue arises when we are using angular-moment in ionic framework for ios app development(build tested in iphones,  6+). While its ok in android app.

**Comment by urish** [comment]
well, I don't have any iPhone. If you find the cause, please send a pull-request with a fix. I suggest looking at the console and checking whether there are any issues. We had a few iOS-specific issues in the past, such as #2 .
