### ISSUE TITLE
infdig error using amUtc

### ISSUE THREAD

**Issue by james-hoegerl** [urish/angular-moment#207]
`<span class="time" am-time-ago="user.last_seen"></span>`

works fine, but

`<span class="time" am-time-ago="user.last_seen | amUtc"></span>`

Gives me infinite digest error. Is it something I'm doing?

**Comment by urish** [comment]
Perhaps this is actually a bug. Can you please create a small plunkr that reproduces the issue?

Thanks!

**Comment by james-hoegerl** [comment]
Apparently its the version of angular I'm running. (Very old) 

1.2.26

Tested [this plunk](http://plnkr.co/edit/bZaIEg5Bbq0ChOhzeDjf) on 1.3.15 (I believe your required version? Or so it said on plunker) and it works correctly.



I found a work around.

Thanks for the time.

James

**Comment by urish** [comment]
Great, thanks for reporting and updating me about your findings!
