### ISSUE TITLE
upgrading from 0.x to 1.x

### ISSUE THREAD

**Issue by andrew-luhring** [urish/angular-moment#220]
Semver standards state that any update to the leftmost version number is a breaking change; 
our project is currently on 0.10.3 but we want to use angular 1.5.0 (latest);
your .bower.json semver (for 0.10.3) dictates that angular must be less than 1.5.0 but not equal to it; 
is there a reason for this or can we force angular-moment to use 1.5?

Related question-
is there a non-beta branch in this repo somewhere? the only branch I see is master, which is 1.0.0-beta.4

**Comment by urish** [comment]
Yes, 0.10.3 should be compatible with angular 1.5.0. 
There is no non-beta branch, though, I hope to promote the beta to a final 1.0.0 release soon
