### ISSUE TITLE
Update to Angular 1.5.x 

### ISSUE THREAD

**Issue by michaeljota** [urish/angular-moment#221]
Just that.I'll bet there is nothing wrong with the update. :P

**Comment by urish** [comment]
Hi, the latest release (1.0.0-beta.4) declares angular 1.5 as a supported dependency:

https://github.com/urish/angular-moment/commit/2caf202ed000f2683b584adbb4e553826a5786c7

**Comment by michaeljota** [comment]
Thanks! :+1:
