### ISSUE TITLE
bower install angular-moment moment --save ERROR: "ECONFLICT Unable to find suitable version for moment"

### ISSUE THREAD

**Issue by mescalito** [urish/angular-moment#224]
I'm getting an error "ECONFLICT Unable to find suitable version for moment" when running "bower install angular-moment moment --save". Any idea what is going on?

Thanks!

**Comment by priidikvaikla** [comment]
Can you also show how your ```bower.json``` looks like and also the console output before the error is shown?

**Comment by stevengiraldo** [comment]
what was the solution? I have the same problem

**Comment by mescalito** [comment]
easy answer and solution, or at least it was for me. I hope this help u out:
http://stackoverflow.com/questions/35844652/bower-unable-to-find-a-suitable-version-for-angular
