### ISSUE TITLE
`moment.tz.guess()` guess browser timezone

### ISSUE THREAD

**Issue by tsturzl** [urish/angular-moment#229]
It seems I can only provide a static timezone regardless of the timezone of the actual browser. This is incredibly inconvenient for any project which has users in more than one timezone(most projects). It makes timezones almost completely impractical. It would be nice if there were a way to invoke `moment.tz.guess()` instead of passing a timezone string, this function should be able to determine the user's timezone.

If I have time I will send a pull request either today or tomorrow. If someone has a chance to get to it before me please let me know. For now I'm setting the timezone to a static timezone but I know someone will probably ask that to be changed.

**Comment by prasadh13** [comment]
Is this implemented? Can't seem to find it..

**Comment by poppahorse** [comment]
@tsturzl @prasadh13 was this ever resolved?
