### ISSUE TITLE
Time display not updating?

### ISSUE THREAD

**Issue by chrismanderson** [urish/angular-moment#231]
With version `0.10.3`, and a simple 

    $scope.message = {
      text: 'hello world!',
      time: new Date()
    };

and using 

`<span>{{message.time | amDateFormat:'dddd, MMMM Do YYYY, h:mm:ss a'}}</span>`

I'm not seeing the time actually update, no matter how long I wait. That should be happening by default, right?

**Comment by urish** [comment]
Hi, the `amDateFormat` filter does not update automatically. Only the `am-time-ago` directive does...

**Comment by chrismanderson** [comment]
Ok, thanks for that info. Obvious feature request, have the filters update too :). Thanks for getting back to me!

**Comment by urish** [comment]
Unfortunately, in Angular 1.0, filters can't trigger an update, that's the reason `am-time-ago` was implemented as a directive. 

In your case, you can probably work around this by periodically triggering a digest cycle, something like:

`setTimeout(function(){$rootScope.$digest();}, 1000);`

But this will severly affect performance in larger application.
