### ISSUE TITLE
Accessing moment() in your javascript

### ISSUE THREAD

**Issue by lykyd** [urish/angular-moment#236]
Can you give a code example of how to "inject the moment variable into the constructor." ?

**Comment by allocenx** [comment]
Anyone please?

**Comment by lucasgranberg** [comment]
Im not shure I understand the question .

The moment object is provided as an angular constant [here](https://github.com/urish/angular-moment/blob/master/angular-moment.js#L114). I think it is also a global variable but it is cleaner to access it trough angulars dependency injection system.
``` js
angular.module('fooApp')
  .controller('FooCtrl', function ($scope,outlet,moment) {
    console.log(moment().hour(8).minute(0).second(0).toDate());
  });
```
