### ISSUE TITLE
Angular 1.5.3 not be able to find module

### ISSUE THREAD

**Issue by vapits** [urish/angular-moment#238]
Hi there,

I use angular-moment and today we upgrade our application to the latest stable AngularJs 1.5.3.

After that `angular-moment 1.0.0-beta.5` is not working.
In order to make it work I had to go back to `0.10.3` (!!). For me this is the only version of angular moment that works with `angularjs 1.5.3`

Also dependencies used are:
```
"moment": "~2.12.0",
"moment-timezone": "~0.5.3"
```

Is this a know issue? I couldn't find something similar in here.

**Comment by super-ienien** [comment]
Same issue for me

**Comment by urish** [comment]
Does it work with 1.5.2 ?

**Comment by vapits** [comment]
Sorry @urish I can't downgrade to test it :/

**Comment by super-ienien** [comment]
Sorry, finally my issue is not due to angular version.

**Comment by stunaz** [comment]
Having it working fine with 1.5.3

**Comment by sndwch** [comment]
Same issue. Tested with angular 1.5.3 and 1.4.8. I assumed it's an issue related to my low intelligence. 😄 

I'm using npm/gulp/browserify - fixed by including moment and angular-moment scripts directly in index.html instead of browserify'ing them.

**Comment by vapits** [comment]
I manage to test it with 1.5.2 @urish and it works.
The only version that doesn't work with me is 1.5.3
