### ISSUE TITLE
allow moment 2.13.x

### ISSUE THREAD

**Issue by jrencz** [urish/angular-moment#245]
What is reason behind the policy of restricting the wrapper to the latest minor instead of the latest major?

**Comment by dub34** [comment]
Same issue. Can`t install it. Have an error in composer update
 

> Problem 1
>     - The requested package bower-asset/moment >=2.8.0 <2.13.0 exists as bower-asset/moment[2.13.0, dev-develop, dev-master, dev-timrwood/babel-and-rollup, dev-timrwood/remove-old-tasks, dev-timrwood/zone-api] but these are rejected by your constraint.
>   Problem 2
>     - Installation request for bower-asset/angular-moment 1.0.0-beta.5 -> satisfiable by bower-asset/angular-moment[1.0.0-beta.5].
>     - bower-asset/angular-moment 1.0.0-beta.5 requires bower-asset/moment >=2.8.0,<2.13.0 -> no matching package found.

my composer.json require section
"minimum-stability": "dev",
  "prefer-stable": false,
  "require": {
    "php": ">=5.6.0",
    "yiisoft/yii2": "~2.0.6",
    "bower-asset/moment": "2.8.0",
    "bower-asset/angular-moment": "1.0.0-beta.5",
    "bower-asset/angular": "1.5.*",
    "bower-asset/angular-route": "1.5.*",
    "bower-asset/angular-i18n": "*",
    "bower-asset/angular-bootstrap": "1.0.3",
    "bower-asset/angular-ui-router": "0.2.18",
  },

**Comment by urish** [comment]
Fixed in 1.0.0-beta.6
