### ISSUE TITLE
Let duration be passed to $timeout and $interval

### ISSUE THREAD

**Issue by jrencz** [urish/angular-moment#247]
I just came with a conclusion that if I'm using `moment` in my project then it's redundant to write:

```js
$timeout(someFunction, moment.duration(2, 's').asMilliseconds())
```

each time we pass a duration (conceptual) using `Duration` (as in `moment.isDuration(duration) === true`)

I'm about to write 2 simple decorators for both `$interval` and `$timeout` to allow passing `Duration` instead of number of milliseconds like this:

```js
$timeout(someFunction, moment.duration(2, 's')))
```

Do you think it fits into a concept of "angular-moment" (as in "a module to integrate `moment` in an angular app)?

**Comment by jrencz** [comment]
note to self: it would be nice to be able to patch `$timeout.flush` and `$interval.flush` test helpers as well. This might not actually fit here out of the box

**Comment by urish** [comment]
@jrencz I believe that patching `$timeout` and `$interval` is not the right way to go. 

We can either provide `amTimeout` and `amInterval` services, that provide this functionality (e.g. `amTimeout(callback, 5, 's')`) or just create these methods in the `amMoment` service

**Comment by jrencz** [comment]
In my oppinion there's no point in doing that. The point is to reduce number of services one has to remember of, not add another 1 or 2.

**Comment by jrencz** [comment]
@urish since `Duration` object has [`valueOf` implemented](https://github.com/moment/moment/blob/2749f08a24056f93dd2208f2744f21b35f6cd999/src/lib/duration/prototype.js#L26) and [it returns number of milliseconds](https://github.com/moment/moment/blob/2749f08a24056f93dd2208f2744f21b35f6cd999/src/lib/duration/as.js#L33-L40) and [angular passes the delay argument directly to browser's setTimeout](https://github.com/angular/angular.js/blob/3b714740fdc2b97c2375324ee46b222c23c06bf5/src/ng/browser.js#L322-L325) which calls `valueOf` internally (for that one I haven't found a source actually so it has to be checked if all browsers behave this way).

So it's probable that it's save to pass a duration directly to `$timeout` and `$interval`

**Comment by jrencz** [comment]
Ok, I've got a quote for the last part:

http://www.w3.org/TR/2011/WD-html5-20110525/timers.html#timers

> When the above methods are to get the timeout, they must run the following steps:
> 1. Let timeout be the second argument to the method, or zero if the argument was omitted.
> 2. Apply the ToString() abstract operation to timeout, and let timeout be the result. [[ECMA262](http://www.w3.org/TR/2011/WD-html5-20110525/references.html#refsECMA262)]
> **3. Apply the ToNumber() abstract operation to timeout, and let timeout be the result. [[ECMA262](http://www.w3.org/TR/2011/WD-html5-20110525/references.html#refsECMA262)]**
> 4. If timeout is an Infinity value, a Not-a-Number (NaN) value, or negative, let timeout be zero.
> 5. Round timeout down to the nearest integer, and let timeout be the result.
> 6. Return timeout.

So:

http://www.ecma-international.org/ecma-262/6.0/index.html#sec-tonumber
calls http://www.ecma-international.org/ecma-262/6.0/index.html#sec-toprimitive
which calls `valueOf`

**Comment by urish** [comment]
So it seems like our job is already done, that's great :-)
