### ISSUE TITLE
`require` is not defined in Chrome 50

### ISSUE THREAD

**Issue by camolin3** [urish/angular-moment#248]
I am building an Ionic app, and running my tests with Karma in Chrome. After installing `angular-moment` with bower, I got this error from Karma:

```bash
Chrome 50.0.2661 (Linux 0.0.0)
Uncaught ReferenceError: require is not defined
at http://localhost:9876/base/www/lib/angular-moment/angular-moment.js?c9396fdf87d2bfaeb2209190bc42b13da9d15695:627
```

So none of my tests run anymore. I noticed that I could modify line 627 to detect if `require` is available, going from this
```javascript
} else if (typeof module !== 'undefined' && module && module.exports) {
```

to this
```javascript
} else if (typeof module !== 'undefined' && module && module.exports && (module.require || window.require)) {
```

**Comment by urish** [comment]
Hi,

I'm wondering how comes that both `module` and `module.exports` are defined for you?
If I open chrome dev tools and type `module`, it doesn't seem to be defined....

Thanks!

**Comment by camolin3** [comment]
Hi Uri,
I noticed Karma was including `angular-mocks`, which defined `window.module`.
Now I am loading `angular-moment` before this "dev" package.
Thank you!
