### ISSUE TITLE
Fractional time with zones fails to parse correctly

### ISSUE THREAD

**Issue by revmischa** [urish/angular-moment#249]
This is a valid datetime:
2016-05-21T00:47:46.873709+00:00

Error: [$parse:syntax] Syntax Error: Token 'T01' is an unexpected token at column 11 of the expression [2016-05-21T01:00:59.390463+00:00] starting at [T01:00:59.390463+00:00]

> "If necessary for a particular application, the standard supports the addition of a decimal fraction to the smallest time value in the representation."
https://en.wikipedia.org/wiki/ISO_8601

**Comment by urish** [comment]
Seems like an error thrown by the Angular template compiler. You probably need to wrap the string you are passing with quotes.
