### ISSUE TITLE
Update v0.10.x to support Angular 1.5.5

### ISSUE THREAD

**Issue by stowball** [urish/angular-moment#250]
Doing a `bower install angular-moment --save` installs v0.10.3, whose Angular dependency is >=1.2.0 <1.5.0.

It would be good to publish a new version to support v1.5.5 so we don't get warnings like:

```sh
Please note that,
    angular-moment#0.10.3, angular-moment#0.10.3 depends on angular#>=1.2.0 <1.5.0 which resolved to angular#1.4.10
    angular-animate#1.5.5, angular-aria#1.5.5, angular-messages#1.5.5, angular-mocks#1.5.5, angular-sanitize#1.5.5 depends on angular#1.5.5 which resolved to angular#1.5.5
```

**Comment by adest** [comment]
+1
We also face the same issue.

**Comment by urish** [comment]
Hi, you can install the latest beta 1.0.0-beta.6 which supports angular 1.5. I hope to release the final 1.0.0 soon.
