### ISSUE TITLE
Main attribute in package.json

### ISSUE THREAD

**Issue by okayawright** [urish/angular-moment#257]
Can you please add the attribute:
"main": "angular-momentjs.js"
in your package.json so that some modules like node-resolve for Gulp https://github.com/substack/node-resolve can find the entry point in your component.
Cheers.

**Comment by urish** [comment]
yes, can you please send a PR for that?

thanks,
Uri

**Comment by Chyzwar** [comment]
Imo better will be to follow with what other are doing. 

ngAria, ngMaterial, ngAnimate all have index.js all have:
```js
require('./angular-animate');
module.exports = 'ngAnimate';
```
This will initalise module and provide a name to be used in module definition like:

```js
import ngAnimate from 'angular-animate

angular.module('myApp' , [
 ngAnimate
]);
```

This shuld also work for commonjs, es6, browserity.

**Comment by urish** [comment]
The package.json entry is there

**Comment by Chyzwar** [comment]
But it do not export name of module. There no simple way to use this module with clj or ES modules.
Angular1 have this silly convention of adding modules by name and hoping that they are available in runtime. When used with with ESModules I would like to:

```js
import ngMoment from 'angular-moment';

angular.module('myApp', [
    ngMoment
]);
````

I pointed to ngAnimate solution that is widely used in core. For CLJ and ES Modules what is needed is name of module not module itself. 

I can see in release notes that for AMD module name is exported, it would be also the case for CJS?
