### ISSUE TITLE
With setting a `title` attribute mayhaps

### ISSUE THREAD

**Issue by peterbe** [urish/angular-moment#31]
I'm currently using angular-moment like this:

``` html
<time ng-if="event.archive_time" title="{{ formatDate(event.archive_time) }}" am-time-ago="event.archive_time"></time>
```

It works great because it displays it as "2 hours ago" but when you hover over the text you get the full, accurate, description of the date. 

Could this be something built into angular-moment perhaps?

**Comment by mnapoli** [comment]
+1 for such a feature!
