### ISSUE TITLE
Issue using angular-moment and requirejs

### ISSUE THREAD

**Issue by antho1404** [urish/angular-moment#36]
Because momentjs lib can check if the define function (from requirejs) exists and in this case create a module for requirejs, the moment variable is not global and so cannot be accessible using $window.moment so this create some execution errors.

One fix actually is to load requirejs after momentjs but I think this should be fix

momentjs: v2.5.1
angular-moment: v0.6.2

**Comment by urish** [comment]
@WilliamCarter, seems like you have nailed it. Can you please send a pull request with the suggested change?

**Comment by pspi** [comment]
+1

**Comment by astyfx** [comment]
@WilliamCarter thanks for the solution.
In my case, it worked by change the name of library in paths

```
'angularMoment': '../bower_components/angular-moment/angular-moment.min',
```
to
```
''angular-moment': '../bower_components/angular-moment/angular-moment.min',
```

**Comment by kirangsa** [comment]
In my case nothing is working 


Mu requre file is this

require.config({
    baseUrl: 'js',
    paths: {
        'jquery':'lib/jquery',
        'jqueryui':'lib/jquery-ui.min',
        'modernzr': 'lib/modernizr',          
        'angular': 'lib/angular.min',
        'angular-route': 'lib/angular-route.min',          
        'angular-animate': 'lib/angular-animate.min',
        'app-start': 'custom/common/app-start',
        'app-route': 'custom/common/app-route',
        'factory': 'custom/common/factory',
        'filter': 'custom/common/filter',
        'constants': 'custom/common/constants',
        /*User defined Files to go here*/
        'bootstrap': 'lib/ui-bootstrap-tpls-0.12.1.min',
        'selectBoxIt': 'lib/jquery.selectBoxIt.min',
        "moment": 'lib/moment',
        "angular-moment": 'lib/angular-moment',
        'login': 'custom/controllers/loginCtrl',
        'dashboard' :'custom/controllers/dashboardCtrl',
        'projectView' :'custom/controllers/projectViewCtrl',
        'projectViewDir' :'custom/directives/projectViewDir'
    },
    shim: {
        'angular-animate': ['angular'],
        'angular-route': ['angular', 'angular-animate'],
        'app-start': ['angular-route'],
        /*User defined files to go here*/
        'login': ['angular'],
        'dashboard': ['angular'],
        'projectView' :['angular'],
        'bootstrap':['jquery'],
        'selectBoxIt': ['jquery', 'jqueryui']
        
    },
    wrapShim: true
});

require(['app-start']);




and app start file is this

define(['app-route', 'jquery', 'jqueryui', 'moment', 'angular-moment', 'bootstrap', 'selectBoxIt', 'factory', 'projectViewDir', 'constants', 'filter', 'login', 'dashboard', 'projectView'], function (router, jquery, jqueryui, moment,angularMoment, bootstrap, selectBoxIt, factory, projectViewDir, constants, filter, loginModu, dashboardModu, project) {
    'use strict';
    console.log('in application');
   
    var appName = 'ongc-app',
        depends = ['ngRoute', 'ngAnimate', router.name, factory.name, projectViewDir.name, constants.name, filter.name, loginModu.name, dashboardModu.name, project.name],
        app = angular.module(appName, depends);
    angular.bootstrap(document, [appName]);

});



Please anyone help me on this
