### ISSUE TITLE
Is there a way to format the "am-time-ago" directive?

### ISSUE THREAD

**Issue by moroshko** [urish/angular-moment#44]
Hi,

I wonder if it is possible to change the formatting to be like this: "1d", "5d", "3h", etc.

http://stackoverflow.com/q/22964767/247243

Thanks!

**Comment by seiyria** [comment]
I have an issue slightly related to this: I want to get certain `am-time-ago` in strictly hours. However, I don't want to affect the other `am-time-ago`'s on the page. Is it possible to do this workaround but not pollute the other instances?

**Comment by ajayreddy56** [comment]
Hi Urish,

i facing an issue with `moment.lang('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s",
        s:  "%ds",
        m:  "1m",
        mm: "%dm",
        h:  "1h",
        hh: "%dh",
        d:  "1d",
        dd: "%dd",
        M:  "30d",
        MM: function (number) {
          return number * 30 + 'd';
        },
        y:  "365d",
        yy: function (number) {
          return number * 365 + 'd';
        }
    }
});
`
when i post , time starting from 5s,4s,3s,2s,1s, then it's displaying 2s,3s,
can you look into this  @urish

**Comment by urish** [comment]
@ajayreddy56 sorry, I don't have time to look into this - you can ask in stackoverflow or in moment's repo: https://github.com/moment/moment/issues
