### ISSUE TITLE
more preprocessors: Unix Timestamp / Date.now()

### ISSUE THREAD

**Issue by rriemann** [urish/angular-moment#63]
In my angular app I'm using Linux Timestamps generated by Date.now().

Is it possible to add the adequate preprocessor for this? (simply /1000 to existing unix preprocessor). moment.js itself supports both as well.

Best,
Robert

**Comment by roberthunt** [comment]
It appears to work by default as @caseprince mentioned, I store time and date in a database as a long integer representing milliseconds since unix epoch in UTC and it was able to format them fine using:
`{{myObj.unixMilliseconds | amDateFormat:'dddd, MMMM Do YYYY, h:mm:ss a'}}`

**Comment by urish** [comment]
These time stamps are indeed supported natively. In addition, as of 1.0.0, you can use the `amParse` filter to specify a custom format.
