### ISSUE TITLE
customize output 

### ISSUE THREAD

**Issue by enapupe** [urish/angular-moment#72]
I was trying to achieve an output like this: `<b>7</b> days ago`, `7 <small>days ago</small>` or anything similar to be able to apply some css.  After a look at the source I couldn't find a way. Would you point a way to do this? Is it possible to do without modifying your code, just re-declaring the directive?

My current code is:
`<span class="adate" am-time-ago="history.date"></span>`
also note that  where I added `days ago` could've been `seconds ago`, `months ago`, etc

**Comment by urish** [comment]
@TheWrongAlice see #44, it shows how to do this.

@enapupe Overiding `humanize()` (as outlined in #44) should do the trick, though, we currently update the element's text (and not innerHTML).

**Comment by enapupe** [comment]
@urish Yeah, that's a deal breaker..
I'm gonna stick with my  modified version of angular-moment for now.

**Comment by urish** [comment]
@enapupe no problem... Closing the issue for now
