### ISSUE TITLE
Moment() constructor with non-ISO string is deprecated

### ISSUE THREAD

**Issue by DerekDomino** [urish/angular-moment#77]
When using an angular-moment filter such as `amDateFormat`, a deprecation warning is logged:

````
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
````

The following lines plead guilty:
 * https://github.com/urish/angular-moment/blob/62b9f6027ebcc9d95ab07626a6d80ede4b170c65/angular-moment.js#L361
 * https://github.com/urish/angular-moment/blob/62b9f6027ebcc9d95ab07626a6d80ede4b170c65/angular-moment.js#L383

**Comment by pursual** [comment]
+1

**Comment by urish** [comment]
Well, did you pass an ISO8601-formatted string or a Date object to the filter?

See http://stackoverflow.com/a/23376374/830623

**Comment by pursual** [comment]
Yeah that part is obvious, but how would you do this when using amdate
filter?

**Comment by urish** [comment]
Two possible solutions:

Either make sure your date is already a date object / in ISO-8601 format (for example, in your controller code), either define a custom preprocessor in `amMoment.preprocessor` and pass it as an argument to the relevant filter.

**Comment by tomasescobar** [comment]
A nice solution is to create a filter and use it before `amDateFormat` to parse the date string:

```
angular.module('app').filter('parseDate', function() {
	return function(value) {
		return Date.parse(value);
	};
});
```

Then you can just use it like this:
```
{{ ctrl.date | parseDate | amDateFormat:'MMMM YYYY' }}
```
