### ISSUE TITLE
Moment is undefined

### ISSUE THREAD

**Issue by szantner** [urish/angular-moment#79]
Using angularjs, node-webkit and angular-moment together I always got errors related to moment being undefined. 

As I changed 

`.constant('moment', moment)`

to

`.constant('moment', (typeof global !== 'undefined' ? global : this).moment)`

in angular-moment.js it stopped to complain. I don't know if it makes any problem in other environments though.

**Comment by kitbrennan90** [comment]
This still isn't fixed. I have submitted a pull request: https://github.com/urish/angular-moment/pull/133

**Comment by iCoolchar** [comment]
I also get the issue. I run:
npm install moment
var moment = require("moment");

but when I webpack it and open the browser, it said : 
Uncaught ReferenceError: moment is not defined

Any one can help? Thanks!

**Comment by patribezek** [comment]
I have the same issue, the solution doesn't work in my project

**Comment by maxchernin** [comment]
same issue for me.

**Comment by VanHumbeeckA** [comment]
I solved it for my project. The issue is related to Webpack, and is similar to an issue where the jQuery global is not being found.
When using webpack, and you need to define some globals, don't use the es6 import statement, but use the following syntax
```
window.jQuery = window.$ = require('../../node_modules/jquery/dist/jquery.min');
window.moment = require('moment');
```

**Comment by smichaud** [comment]
@vanhumbeecka Thank you for your reply. Not very clean, but it solves my problem. Here what I did: 
`
import moment from 'moment/moment';
window.moment = moment;
`

**Comment by jmliz** [comment]
@vanhumbeecka that works for me, thank you.
