### ISSUE TITLE
Is there a directive available for converting to utc to local time?

### ISSUE THREAD

**Issue by chetanra** [urish/angular-moment#81]
Didn't see in the examples on the main page.  If not present, would you mind adding it or would you accept the change if I implement?

**Comment by jeevasusej** [comment]
showing wrongly.
My utc time is 2016-12-19T13:10:29.317

Local time (converted through ur code) is 12.19.2016 18:40:29

But time ago (am-time-ago="item.createdOn") is showing wrong value.
_6 hours ago_
