### ISSUE TITLE
Timezone offset without moment-timezone.js dependency

### ISSUE THREAD

**Issue by manikantag** [urish/angular-moment#82]
Hi,

It is possible to display the date with configured timezone offset without having moment-timezone.js dependency, using `moment(..).zone(..)` method.

Ex: 

	.filter('amDateFormat', ['moment', 'amMoment', function (moment, amMoment) {
		return function (value, format, preprocess) {
			...
			value = amMoment.preprocessDate(value, preprocess);
			var date = moment(value).zone("+0530"); // offset dates by +05:30 hrs
			if (!date.isValid()) {
				return '';
			}
			return amMoment.applyTimezone(date).format(format);
		};
	}])

Are there any other advantages using moment-timezone instead of `moment().zone()` method.

Thanks.

**Comment by urish** [comment]
Implemented as of v0.10.2. See #151 for details.

**Comment by manikantag** [comment]
Aaahhh! Thanks a lot. Now I can save few bytes by removing moment-timezone.js

But are there any additional benefits of using moment-timezone.js other than using timezone string names?

**Comment by urish** [comment]
You're welcome :)

Not that I am aware of...
