### ISSUE TITLE
Can timezone be non-constant?

### ISSUE THREAD

**Issue by hoopes** [urish/angular-moment#92]
I'd really like the option of being able to switch timezone dynamically. Is that an option? Any guidance for your preferred implementation of that (if I were to find some time to do it)?

**Comment by bierdok** [comment]
+1 for ```amMoment.changeTimezone([string])``` !

**Comment by bierdok** [comment]
it can be useful with this https://github.com/cmmartin/ngTimezone

**Comment by bierdok** [comment]
you can do that
```
angular
    .module('helloworld.moment', [
        'angularMoment',
        'ngTimezone'
    ]).run(function($timezone, angularMomentConfig) {
        angularMomentConfig.preprocess = 'utc';
        angularMomentConfig.timezone = $timezone.getName();
    });

```

**Comment by phongmedia** [comment]
I second @jirihelmich - there is no constant time zones in the app I'm building. I need the option to switch the timezone dynamically using a filter.
