### ISSUE TITLE
angular filters should be stateful

### ISSUE THREAD

**Issue by eliranhh** [urish/angular-moment#97]
just like angular-translate
if you're using angular ^1.3
you cannot change lang on the fly, filters will not update.

fix example:

instead of:
.filter('amCalendar', ['moment', 'amMoment', function (moment, amMoment) {
                return function (value, preprocess) {
                    if (typeof value === 'undefined' || value === null) {
                        return '';
                    }

```
                value = amMoment.preprocessDate(value, preprocess);
                var date = moment(value);
                if (!date.isValid()) {
                    return '';
                }

                return amMoment.applyTimezone(date).calendar();
            };
        }])
```

use:

.filter('amCalendar', ['moment', 'amMoment', function (moment, amMoment) {
                var func = function (value, preprocess) {
                    if (typeof value === 'undefined' || value === null) {
                        return '';
                    }

```
                value = amMoment.preprocessDate(value, preprocess);
                var date = moment(value);
                if (!date.isValid()) {
                    return '';
                }

                return amMoment.applyTimezone(date).calendar();
            };
            func.$stateful = true;
            return func;
        }])
```

**Comment by urish** [comment]
Fixed as of angular-moment 0.9.0
